#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Running checks before committing'

# cd frontend
# npm run pre-commit
# npm run format

# Enable all checks below after fixing all type errors

# Check ESLint Standards & TS errors
# npm run lint ||
#   (
#     echo '😤 ESLint Check Failed. 😤
#     Make the required changes listed above, add changes and try to commit again.'
#     false
#   )


declare IS_APP_FOLDER_CHANGE=$(git show --name-only -r --stat --oneline HEAD^^..HEAD | grep 'frontend/')

echo "IS_APP_FOLDER_CHANGE  --> + $IS_APP_FOLDER_CHANGE"

if [[ $IS_APP_FOLDER_CHANGE ]]; then cd frontend && npm run lint && npm run format && cd ..; fi