// @ts-nocheck
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CircleForms
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  FullPostContract,
  FullPostContractFromJSON,
  FullPostContractFromJSONTyped,
  FullPostContractToJSON
} from "./FullPostContract";
import {
  Submission,
  SubmissionFromJSON,
  SubmissionFromJSONTyped,
  SubmissionToJSON
} from "./Submission";

/**
 *
 * @export
 * @interface AnswerFullPostContract
 */
export interface AnswerFullPostContract {
  /**
   *
   * @type {Array<Submission>}
   * @memberof AnswerFullPostContract
   */
  answer?: Array<Submission> | null;
  /**
   *
   * @type {FullPostContract}
   * @memberof AnswerFullPostContract
   */
  post?: FullPostContract;
}

export function AnswerFullPostContractFromJSON(json: any): AnswerFullPostContract {
  return AnswerFullPostContractFromJSONTyped(json, false);
}

export function AnswerFullPostContractFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AnswerFullPostContract {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    answer: !exists(json, "answer")
      ? undefined
      : json["answer"] === null
      ? null
      : (json["answer"] as Array<any>).map(SubmissionFromJSON),
    post: !exists(json, "post") ? undefined : FullPostContractFromJSON(json["post"])
  };
}

export function AnswerFullPostContractToJSON(value?: AnswerFullPostContract | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    answer:
      value.answer === undefined
        ? undefined
        : value.answer === null
        ? null
        : (value.answer as Array<any>).map(SubmissionToJSON),
    post: FullPostContractToJSON(value.post)
  };
}
