// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CircleForms
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  AnswerContract,
  AnswerContractFromJSON,
  AnswerContractFromJSONTyped,
  AnswerContractToJSON
} from "./AnswerContract";
import {
  PostContract,
  PostContractFromJSON,
  PostContractFromJSONTyped,
  PostContractToJSON
} from "./PostContract";

/**
 *
 * @export
 * @interface AnswerPostContract
 */
export interface AnswerPostContract {
  /**
   *
   * @type {AnswerContract}
   * @memberof AnswerPostContract
   */
  answer?: AnswerContract;
  /**
   *
   * @type {PostContract}
   * @memberof AnswerPostContract
   */
  post?: PostContract;
}

export function AnswerPostContractFromJSON(json: any): AnswerPostContract {
  return AnswerPostContractFromJSONTyped(json, false);
}

export function AnswerPostContractFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AnswerPostContract {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    answer: !exists(json, "answer") ? undefined : AnswerContractFromJSON(json["answer"]),
    post: !exists(json, "post") ? undefined : PostContractFromJSON(json["post"])
  };
}

export function AnswerPostContractToJSON(value?: AnswerPostContract | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    answer: AnswerContractToJSON(value.answer),
    post: PostContractToJSON(value.post)
  };
}
