// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CircleForms
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GradeCounts
 */
export interface GradeCounts {
    /**
     * 
     * @type {number}
     * @memberof GradeCounts
     */
    ss?: number;
    /**
     * 
     * @type {number}
     * @memberof GradeCounts
     */
    ssh?: number;
    /**
     * 
     * @type {number}
     * @memberof GradeCounts
     */
    s?: number;
    /**
     * 
     * @type {number}
     * @memberof GradeCounts
     */
    sh?: number;
    /**
     * 
     * @type {number}
     * @memberof GradeCounts
     */
    a?: number;
}

export function GradeCountsFromJSON(json: any): GradeCounts {
    return GradeCountsFromJSONTyped(json, false);
}

export function GradeCountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GradeCounts {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ss': !exists(json, 'ss') ? undefined : json['ss'],
        'ssh': !exists(json, 'ssh') ? undefined : json['ssh'],
        's': !exists(json, 's') ? undefined : json['s'],
        'sh': !exists(json, 'sh') ? undefined : json['sh'],
        'a': !exists(json, 'a') ? undefined : json['a'],
    };
}

export function GradeCountsToJSON(value?: GradeCounts | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ss': value.ss,
        'ssh': value.ssh,
        's': value.s,
        'sh': value.sh,
        'a': value.a,
    };
}
