// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CircleForms
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Kudosu
 */
export interface Kudosu {
    /**
     * 
     * @type {number}
     * @memberof Kudosu
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof Kudosu
     */
    available?: number;
}

export function KudosuFromJSON(json: any): Kudosu {
    return KudosuFromJSONTyped(json, false);
}

export function KudosuFromJSONTyped(json: any, ignoreDiscriminator: boolean): Kudosu {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'total': !exists(json, 'total') ? undefined : json['total'],
        'available': !exists(json, 'available') ? undefined : json['available'],
    };
}

export function KudosuToJSON(value?: Kudosu | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total': value.total,
        'available': value.available,
    };
}
