// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CircleForms
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MongoDbRange,
    MongoDbRangeFromJSON,
    MongoDbRangeFromJSONTyped,
    MongoDbRangeToJSON,
} from './MongoDbRange';

/**
 * 
 * @export
 * @interface Limitations
 */
export interface Limitations {
    /**
     * 
     * @type {MongoDbRange}
     * @memberof Limitations
     */
    rank?: MongoDbRange;
    /**
     * 
     * @type {MongoDbRange}
     * @memberof Limitations
     */
    pp?: MongoDbRange;
}

export function LimitationsFromJSON(json: any): Limitations {
    return LimitationsFromJSONTyped(json, false);
}

export function LimitationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Limitations {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rank': !exists(json, 'rank') ? undefined : MongoDbRangeFromJSON(json['rank']),
        'pp': !exists(json, 'pp') ? undefined : MongoDbRangeFromJSON(json['pp']),
    };
}

export function LimitationsToJSON(value?: Limitations | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rank': MongoDbRangeToJSON(value.rank),
        'pp': MongoDbRangeToJSON(value.pp),
    };
}
