// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CircleForms
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StatisticsRulesets,
    StatisticsRulesetsFromJSON,
    StatisticsRulesetsFromJSONTyped,
    StatisticsRulesetsToJSON,
} from './StatisticsRulesets';

/**
 * 
 * @export
 * @interface MinimalOsuUserContract
 */
export interface MinimalOsuUserContract {
    /**
     * 
     * @type {string}
     * @memberof MinimalOsuUserContract
     */
    avatar_url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MinimalOsuUserContract
     */
    username?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MinimalOsuUserContract
     */
    country_code?: string | null;
    /**
     * 
     * @type {StatisticsRulesets}
     * @memberof MinimalOsuUserContract
     */
    statistics_ruleset?: StatisticsRulesets;
}

export function MinimalOsuUserContractFromJSON(json: any): MinimalOsuUserContract {
    return MinimalOsuUserContractFromJSONTyped(json, false);
}

export function MinimalOsuUserContractFromJSONTyped(json: any, ignoreDiscriminator: boolean): MinimalOsuUserContract {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'avatar_url': !exists(json, 'avatar_url') ? undefined : json['avatar_url'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'country_code': !exists(json, 'country_code') ? undefined : json['country_code'],
        'statistics_ruleset': !exists(json, 'statistics_ruleset') ? undefined : StatisticsRulesetsFromJSON(json['statistics_ruleset']),
    };
}

export function MinimalOsuUserContractToJSON(value?: MinimalOsuUserContract | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'avatar_url': value.avatar_url,
        'username': value.username,
        'country_code': value.country_code,
        'statistics_ruleset': StatisticsRulesetsToJSON(value.statistics_ruleset),
    };
}
