// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CircleForms
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MongoDbRange
 */
export interface MongoDbRange {
    /**
     * 
     * @type {number}
     * @memberof MongoDbRange
     */
    start?: number;
    /**
     * 
     * @type {number}
     * @memberof MongoDbRange
     */
    end?: number;
}

export function MongoDbRangeFromJSON(json: any): MongoDbRange {
    return MongoDbRangeFromJSONTyped(json, false);
}

export function MongoDbRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MongoDbRange {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'start': !exists(json, 'start') ? undefined : json['start'],
        'end': !exists(json, 'end') ? undefined : json['end'],
    };
}

export function MongoDbRangeToJSON(value?: MongoDbRange | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start': value.start,
        'end': value.end,
    };
}
