/* tslint:disable */
/* eslint-disable */
/**
 * CircleForms
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OsuAnswerContract
 */
export interface OsuAnswerContract {
    /**
     * 
     * @type {string}
     * @memberof OsuAnswerContract
     */
    avatarUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OsuAnswerContract
     */
    username?: string | null;
    /**
     * 
     * @type {any}
     * @memberof OsuAnswerContract
     */
    statistics?: any | null;
    /**
     * 
     * @type {any}
     * @memberof OsuAnswerContract
     */
    countryCode?: any | null;
}

export function OsuAnswerContractFromJSON(json: any): OsuAnswerContract {
    return OsuAnswerContractFromJSONTyped(json, false);
}

export function OsuAnswerContractFromJSONTyped(json: any, ignoreDiscriminator: boolean): OsuAnswerContract {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'avatarUrl': !exists(json, 'avatar_url') ? undefined : json['avatar_url'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'statistics': !exists(json, 'statistics') ? undefined : json['statistics'],
        'countryCode': !exists(json, 'country_code') ? undefined : json['country_code'],
    };
}

export function OsuAnswerContractToJSON(value?: OsuAnswerContract | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'avatar_url': value.avatarUrl,
        'username': value.username,
        'statistics': value.statistics,
        'country_code': value.countryCode,
    };
}

