// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CircleForms
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  Accessibility,
  AccessibilityFromJSON,
  AccessibilityFromJSONTyped,
  AccessibilityToJSON
} from "./Accessibility";
import { Gamemode, GamemodeFromJSON, GamemodeFromJSONTyped, GamemodeToJSON } from "./Gamemode";
import {
  Limitations,
  LimitationsFromJSON,
  LimitationsFromJSONTyped,
  LimitationsToJSON
} from "./Limitations";
import { Question, QuestionFromJSON, QuestionFromJSONTyped, QuestionToJSON } from "./Question";

/**
 *
 * @export
 * @interface PostWithQuestionsContract
 */
export interface PostWithQuestionsContract {
  /**
   *
   * @type {boolean}
   * @memberof PostWithQuestionsContract
   */

  /**
   *
   * @type {Array<Question>}
   * @memberof PostWithQuestionsContract
   */

  /**
   *
   * @type {string}
   * @memberof PostWithQuestionsContract
   */

  /**
   *
   * @type {string}
   * @memberof PostWithQuestionsContract
   */

  /**
   *
   * @type {boolean}
   * @memberof PostWithQuestionsContract
   */

  /**
   *
   * @type {Date}
   * @memberof PostWithQuestionsContract
   */

  /**
   *
   * @type {string}
   * @memberof PostWithQuestionsContract
   */

  /**
   *
   * @type {string}
   * @memberof PostWithQuestionsContract
   */

  /**
   *
   * @type {string}
   * @memberof PostWithQuestionsContract
   */

  /**
   *
   * @type {string}
   * @memberof PostWithQuestionsContract
   */

  /**
   *
   * @type {string}
   * @memberof PostWithQuestionsContract
   */
 
  /**
   *
   * @type {Gamemode}
   * @memberof PostWithQuestionsContract
   */

  /**
   *
   * @type {boolean}
   * @memberof PostWithQuestionsContract
   */

  /**
   *
   * @type {Date}
   * @memberof PostWithQuestionsContract
   */

  /**
   *
   * @type {Accessibility}
   * @memberof PostWithQuestionsContract
   */

  /**
   *
   * @type {Limitations}
   * @memberof PostWithQuestionsContract
   */

  /**
   *
   * @type {number}
   * @memberof PostWithQuestionsContract
   */
  answerCount?: number;
}

export function PostWithQuestionsContractFromJSON(json: any): PostWithQuestionsContract {
  return PostWithQuestionsContractFromJSONTyped(json, false);
}

export function PostWithQuestionsContractFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PostWithQuestionsContract {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    allowAnswerEdit: !exists(json, "allow_answer_edit") ? undefined : json["allow_answer_edit"],
    questions: !exists(json, "questions")
      ? undefined
      : json["questions"] === null
      ? null
      : (json["questions"] as Array<any>).map(QuestionFromJSON),
    id: !exists(json, "id") ? undefined : json["id"],
    authorId: !exists(json, "author_id") ? undefined : json["author_id"],
    isActive: !exists(json, "is_active") ? undefined : json["is_active"],
    activeTo: !exists(json, "active_to") ? undefined : new Date(json["active_to"]),
    icon: !exists(json, "icon") ? undefined : json["icon"],
    banner: !exists(json, "banner") ? undefined : json["banner"],
    title: !exists(json, "title") ? undefined : json["title"],
    description: !exists(json, "description") ? undefined : json["description"],
    excerpt: !exists(json, "excerpt") ? undefined : json["excerpt"],
    gamemode: !exists(json, "gamemode") ? undefined : GamemodeFromJSON(json["gamemode"]),
    published: !exists(json, "published") ? undefined : json["published"],
    publishTime: !exists(json, "publish_time")
      ? undefined
      : json["publish_time"] === null
      ? null
      : new Date(json["publish_time"]),
    accessibility: !exists(json, "accessibility")
      ? undefined
      : AccessibilityFromJSON(json["accessibility"]),
    limitations: !exists(json, "limitations")
      ? undefined
      : LimitationsFromJSON(json["limitations"]),
    answerCount: !exists(json, "answer_count") ? undefined : json["answer_count"]
  };
}

export function PostWithQuestionsContractToJSON(value?: PostWithQuestionsContract | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    allow_answer_edit: value.allowAnswerEdit,
    questions:
      value.questions === undefined
        ? undefined
        : value.questions === null
        ? null
        : (value.questions as Array<any>).map(QuestionToJSON),
    id: value.id,
    author_id: value.authorId,
    is_active: value.isActive,
    active_to: value.activeTo === undefined ? undefined : value.activeTo.toISOString(),
    icon: value.icon,
    banner: value.banner,
    title: value.title,
    description: value.description,
    excerpt: value.excerpt,
    gamemode: GamemodeToJSON(value.gamemode),
    published: value.published,
    publish_time:
      value.publishTime === undefined
        ? undefined
        : value.publishTime === null
        ? null
        : value.publishTime.toISOString(),
    accessibility: AccessibilityToJSON(value.accessibility),
    limitations: LimitationsToJSON(value.limitations),
    answer_count: value.answerCount
  };
}
