// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CircleForms
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RankHistory
 */
export interface RankHistory {
  /**
   *
   * @type {string}
   * @memberof RankHistory
   */
  mode?: string | null;
  /**
   *
   * @type {Array<number>}
   * @memberof RankHistory
   */
  data?: Array<number> | null;
}

export function RankHistoryFromJSON(json: any): RankHistory {
  return RankHistoryFromJSONTyped(json, false);
}

export function RankHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RankHistory {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    mode: !exists(json, "mode") ? undefined : json["mode"],
    data: !exists(json, "data") ? undefined : json["data"]
  };
}

export function RankHistoryToJSON(value?: RankHistory | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    mode: value.mode,
    data: value.data
  };
}
