// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CircleForms
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  Statistics,
  StatisticsFromJSON,
  StatisticsFromJSONTyped,
  StatisticsToJSON
} from "./Statistics";

/**
 *
 * @export
 * @interface StatisticsRulesets
 */
export interface StatisticsRulesets {
  /**
   *
   * @type {Statistics}
   * @memberof StatisticsRulesets
   */
  osu?: Statistics;
  /**
   *
   * @type {Statistics}
   * @memberof StatisticsRulesets
   */
  taiko?: Statistics;
  /**
   *
   * @type {Statistics}
   * @memberof StatisticsRulesets
   */
  fruits?: Statistics;
  /**
   *
   * @type {Statistics}
   * @memberof StatisticsRulesets
   */
  mania?: Statistics;
}

export function StatisticsRulesetsFromJSON(json: any): StatisticsRulesets {
  return StatisticsRulesetsFromJSONTyped(json, false);
}

export function StatisticsRulesetsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): StatisticsRulesets {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    osu: !exists(json, "osu") ? undefined : StatisticsFromJSON(json["osu"]),
    taiko: !exists(json, "taiko") ? undefined : StatisticsFromJSON(json["taiko"]),
    fruits: !exists(json, "fruits") ? undefined : StatisticsFromJSON(json["fruits"]),
    mania: !exists(json, "mania") ? undefined : StatisticsFromJSON(json["mania"])
  };
}

export function StatisticsRulesetsToJSON(value?: StatisticsRulesets | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    osu: StatisticsToJSON(value.osu),
    taiko: StatisticsToJSON(value.taiko),
    fruits: StatisticsToJSON(value.fruits),
    mania: StatisticsToJSON(value.mania)
  };
}
