// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CircleForms
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  GradeCounts,
  GradeCountsFromJSON,
  GradeCountsFromJSONTyped,
  GradeCountsToJSON
} from "./GradeCounts";
import { Level, LevelFromJSON, LevelFromJSONTyped, LevelToJSON } from "./Level";

/**
 *
 * @export
 * @interface Statistics
 */
export interface Statistics {
  /**
   *
   * @type {Level}
   * @memberof Statistics
   */
  level?: Level;
  /**
   *
   * @type {number}
   * @memberof Statistics
   */
  globalRank?: number;
  /**
   *
   * @type {number}
   * @memberof Statistics
   */
  pp?: number;
  /**
   *
   * @type {number}
   * @memberof Statistics
   */
  rankedScore?: number;
  /**
   *
   * @type {number}
   * @memberof Statistics
   */
  hitAccuracy?: number;
  /**
   *
   * @type {number}
   * @memberof Statistics
   */
  playCount?: number;
  /**
   *
   * @type {number}
   * @memberof Statistics
   */
  playTime?: number;
  /**
   *
   * @type {number}
   * @memberof Statistics
   */
  totalScore?: number;
  /**
   *
   * @type {number}
   * @memberof Statistics
   */
  totalHits?: number;
  /**
   *
   * @type {number}
   * @memberof Statistics
   */
  maximumCombo?: number;
  /**
   *
   * @type {number}
   * @memberof Statistics
   */
  replaysWatchedByOthers?: number;
  /**
   *
   * @type {boolean}
   * @memberof Statistics
   */
  isRanked?: boolean;
  /**
   *
   * @type {GradeCounts}
   * @memberof Statistics
   */
  gradeCounts?: GradeCounts;
  /**
   *
   * @type {number}
   * @memberof Statistics
   */
  countryRank?: number;
}

export function StatisticsFromJSON(json: any): Statistics {
  return StatisticsFromJSONTyped(json, false);
}

export function StatisticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Statistics {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    level: !exists(json, "level") ? undefined : LevelFromJSON(json["level"]),
    globalRank: !exists(json, "global_rank") ? undefined : json["global_rank"],
    pp: !exists(json, "pp") ? undefined : json["pp"],
    rankedScore: !exists(json, "ranked_score") ? undefined : json["ranked_score"],
    hitAccuracy: !exists(json, "hit_accuracy") ? undefined : json["hit_accuracy"],
    playCount: !exists(json, "play_count") ? undefined : json["play_count"],
    playTime: !exists(json, "play_time") ? undefined : json["play_time"],
    totalScore: !exists(json, "total_score") ? undefined : json["total_score"],
    totalHits: !exists(json, "total_hits") ? undefined : json["total_hits"],
    maximumCombo: !exists(json, "maximum_combo") ? undefined : json["maximum_combo"],
    replaysWatchedByOthers: !exists(json, "replays_watched_by_others")
      ? undefined
      : json["replays_watched_by_others"],
    isRanked: !exists(json, "is_ranked") ? undefined : json["is_ranked"],
    gradeCounts: !exists(json, "grade_counts")
      ? undefined
      : GradeCountsFromJSON(json["grade_counts"]),
    countryRank: !exists(json, "country_rank") ? undefined : json["country_rank"]
  };
}

export function StatisticsToJSON(value?: Statistics | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    level: LevelToJSON(value.level),
    global_rank: value.globalRank,
    pp: value.pp,
    ranked_score: value.rankedScore,
    hit_accuracy: value.hitAccuracy,
    play_count: value.playCount,
    play_time: value.playTime,
    total_score: value.totalScore,
    total_hits: value.totalHits,
    maximum_combo: value.maximumCombo,
    replays_watched_by_others: value.replaysWatchedByOthers,
    is_ranked: value.isRanked,
    grade_counts: GradeCountsToJSON(value.gradeCounts),
    country_rank: value.countryRank
  };
}
