// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CircleForms
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Submission
 */
export interface Submission {
  /**
   *
   * @type {string}
   * @memberof Submission
   */
  questionId?: string | null;
  /**
   *
   * @type {Array<string>}
   * @memberof Submission
   */
  answers?: Array<string> | null;
}

export function SubmissionFromJSON(json: any): Submission {
  return SubmissionFromJSONTyped(json, false);
}

export function SubmissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Submission {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    questionId: !exists(json, "question_id") ? undefined : json["question_id"],
    answers: !exists(json, "answers") ? undefined : json["answers"]
  };
}

export function SubmissionToJSON(value?: Submission | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    question_id: value.questionId,
    answers: value.answers
  };
}
