// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CircleForms
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  OsuUserContract,
  OsuUserContractFromJSON,
  OsuUserContractFromJSONTyped,
  OsuUserContractToJSON
} from "./OsuUserContract";

/**
 *
 * @export
 * @interface UserContract
 */
export interface UserContract {
  /**
   *
   * @type {Array<string>}
   * @memberof UserContract
   */
  roles?: Array<string> | null;
  /**
   *
   * @type {string}
   * @memberof UserContract
   */
  id?: string | null;
  /**
   *
   * @type {string}
   * @memberof UserContract
   */
  discord?: string | null;
  /**
   *
   * @type {OsuUserContract}
   * @memberof UserContract
   */
  osu?: OsuUserContract;
}

export function UserContractFromJSON(json: any): UserContract {
  return UserContractFromJSONTyped(json, false);
}

export function UserContractFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserContract {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    roles: !exists(json, "roles") ? undefined : json["roles"],
    id: !exists(json, "id") ? undefined : json["id"],
    discord: !exists(json, "discord") ? undefined : json["discord"],
    osu: !exists(json, "osu") ? undefined : OsuUserContractFromJSON(json["osu"])
  };
}

export function UserContractToJSON(value?: UserContract | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    roles: value.roles,
    id: value.id,
    discord: value.discord,
    osu: OsuUserContractToJSON(value.osu)
  };
}
