// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CircleForms
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UserBadge
 */
export interface UserBadge {
  /**
   *
   * @type {Date}
   * @memberof UserBadge
   */
  awardedAt?: Date;
  /**
   *
   * @type {string}
   * @memberof UserBadge
   */
  description?: string | null;
  /**
   *
   * @type {string}
   * @memberof UserBadge
   */
  imageUrl?: string | null;
  /**
   *
   * @type {string}
   * @memberof UserBadge
   */
  url?: string | null;
}

export function UserBadgeFromJSON(json: any): UserBadge {
  return UserBadgeFromJSONTyped(json, false);
}

export function UserBadgeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserBadge {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    awardedAt: !exists(json, "awarded_at") ? undefined : new Date(json["awarded_at"]),
    description: !exists(json, "description") ? undefined : json["description"],
    imageUrl: !exists(json, "image_url") ? undefined : json["image_url"],
    url: !exists(json, "url") ? undefined : json["url"]
  };
}

export function UserBadgeToJSON(value?: UserBadge | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    awarded_at: value.awardedAt === undefined ? undefined : value.awardedAt.toISOString(),
    description: value.description,
    image_url: value.imageUrl,
    url: value.url
  };
}
