// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CircleForms
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserBadge
 */
export interface UserBadge {
    /**
     * 
     * @type {Date}
     * @memberof UserBadge
     */
    awarded_at?: Date;
    /**
     * 
     * @type {string}
     * @memberof UserBadge
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserBadge
     */
    image_url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserBadge
     */
    url?: string | null;
}

export function UserBadgeFromJSON(json: any): UserBadge {
    return UserBadgeFromJSONTyped(json, false);
}

export function UserBadgeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserBadge {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'awarded_at': !exists(json, 'awarded_at') ? undefined : (new Date(json['awarded_at'])),
        'description': !exists(json, 'description') ? undefined : json['description'],
        'image_url': !exists(json, 'image_url') ? undefined : json['image_url'],
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function UserBadgeToJSON(value?: UserBadge | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'awarded_at': value.awarded_at === undefined ? undefined : (value.awarded_at.toISOString()),
        'description': value.description,
        'image_url': value.image_url,
        'url': value.url,
    };
}
