/* tslint:disable */
/* eslint-disable */
/**
 * CircleForms
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OsuAnswerContract,
    OsuAnswerContractFromJSON,
    OsuAnswerContractFromJSONTyped,
    OsuAnswerContractToJSON,
} from './OsuAnswerContract';

/**
 * 
 * @export
 * @interface UserInAnswerContract
 */
export interface UserInAnswerContract {
    /**
     * 
     * @type {string}
     * @memberof UserInAnswerContract
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInAnswerContract
     */
    discord?: string | null;
    /**
     * 
     * @type {OsuAnswerContract}
     * @memberof UserInAnswerContract
     */
    osu?: OsuAnswerContract;
}

export function UserInAnswerContractFromJSON(json: any): UserInAnswerContract {
    return UserInAnswerContractFromJSONTyped(json, false);
}

export function UserInAnswerContractFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInAnswerContract {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'discord': !exists(json, 'discord') ? undefined : json['discord'],
        'osu': !exists(json, 'osu') ? undefined : OsuAnswerContractFromJSON(json['osu']),
    };
}

export function UserInAnswerContractToJSON(value?: UserInAnswerContract | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'discord': value.discord,
        'osu': OsuAnswerContractToJSON(value.osu),
    };
}

