/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/admin/recache": {
    post: {
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/admin/users": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["UserResponseContract"][];
            "application/json": components["schemas"]["UserResponseContract"][];
            "text/json": components["schemas"]["UserResponseContract"][];
          };
        };
      };
    };
    patch: {
      parameters: {
        query: {
          id?: string;
          roles?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["UserResponseContract"];
            "application/json": components["schemas"]["UserResponseContract"];
            "text/json": components["schemas"]["UserResponseContract"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/admin/posts/mongo/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/admin/posts/mongo": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["PostResponseContract"][];
            "application/json": components["schemas"]["PostResponseContract"][];
            "text/json": components["schemas"]["PostResponseContract"][];
          };
        };
      };
    };
  };
  "/admin/posts/cached": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["PostMinimalResponseContract"][];
            "application/json": components["schemas"]["PostMinimalResponseContract"][];
            "text/json": components["schemas"]["PostMinimalResponseContract"][];
          };
        };
      };
    };
  };
  "/admin/posts/cached/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/OAuth/auth": {
    get: {
      responses: {
        /** Redirect */
        302: never;
      };
    };
  };
  "/OAuth/signout": {
    get: {
      responses: {
        /** Redirect */
        302: never;
      };
    };
  };
  "/posts/page/{page}": {
    get: {
      parameters: {
        path: {
          page: number;
        };
        query: {
          pageSize?: number;
          filter?: components["schemas"]["PostFilter"];
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["PageResponseContract"];
            "application/json": components["schemas"]["PageResponseContract"];
            "text/json": components["schemas"]["PageResponseContract"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/posts/page/pinned": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["PageResponseContract"];
            "application/json": components["schemas"]["PageResponseContract"];
            "text/json": components["schemas"]["PageResponseContract"];
          };
        };
      };
    };
    post: {
      parameters: {
        query: {
          post?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/posts/{id}/answers": {
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Conflict */
        409: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json-patch+json": components["schemas"]["SubmissionContract"][];
          "application/json": components["schemas"]["SubmissionContract"][];
          "text/json": components["schemas"]["SubmissionContract"][];
          "application/*+json": components["schemas"]["SubmissionContract"][];
        };
      };
    };
  };
  "/posts/{id}/files": {
    put: {
      parameters: {
        path: {
          id: string;
        };
        query: {
          query?: components["schemas"]["ImageQuery"];
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "multipart/form-data": {
            /** Format: binary */
            image?: string;
          };
        };
      };
    };
  };
  "/posts": {
    post: {
      responses: {
        /** Success */
        201: unknown;
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
      requestBody: {
        content: {
          "application/json-patch+json": components["schemas"]["PostRequestContract"];
          "application/json": components["schemas"]["PostRequestContract"];
          "text/json": components["schemas"]["PostRequestContract"];
          "application/*+json": components["schemas"]["PostRequestContract"];
        };
      };
    };
  };
  "/posts/{id}/unpublish": {
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/posts/{id}/publish": {
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/posts/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
        query: {
          key?: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json-patch+json": components["schemas"]["PostUpdateRequestContract"];
          "application/json": components["schemas"]["PostUpdateRequestContract"];
          "text/json": components["schemas"]["PostUpdateRequestContract"];
          "application/*+json": components["schemas"]["PostUpdateRequestContract"];
        };
      };
    };
  };
  "/users/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/users/{id}/minimal": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/me/posts": {
    get: {
      responses: {
        /** Success */
        200: unknown;
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/me": {
    get: {
      responses: {
        /** Success */
        200: unknown;
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    /** @enum {string} */
    Accessibility: "Public" | "Link" | "FriendsOnly" | "Whitelist";
    AnswerContract: {
      submissions?: components["schemas"]["Submission"][] | null;
      user?: string | null;
    };
    /** @enum {string} */
    Gamemode: "None" | "Osu" | "Taiko" | "Fruits" | "Mania";
    /** @enum {string} */
    ImageQuery: "Icon" | "Banner";
    Limitations: {
      rank?: components["schemas"]["MongoDbRange"];
      pp?: components["schemas"]["MongoDbRange"];
    };
    MongoDbRange: {
      /** Format: int32 */
      start?: number;
      /** Format: int32 */
      end?: number;
    };
    PageResponseContract: {
      users?: components["schemas"]["UserMinimalResponseContract"][] | null;
      posts?: components["schemas"]["PostMinimalResponseContract"][] | null;
    };
    /** @enum {string} */
    PostFilter: "Both" | "Active" | "Inactive";
    PostMinimalResponseContract: {
      id?: string | null;
      author_id?: string | null;
      is_active?: boolean;
      icon?: string | null;
      banner?: string | null;
      title?: string | null;
      description?: string | null;
      excerpt?: string | null;
      gamemode?: components["schemas"]["Gamemode"];
      /** Format: date-time */
      publish_time?: string;
      accessibility?: components["schemas"]["Accessibility"];
      limitations?: components["schemas"]["Limitations"];
      /** Format: int32 */
      answer_count?: number;
    };
    PostRequestContract: {
      title: string;
      description?: string | null;
      excerpt?: string | null;
      gamemode?: components["schemas"]["Gamemode"];
      accessibility?: components["schemas"]["Accessibility"];
      limitations?: components["schemas"]["Limitations"];
      questions: components["schemas"]["Question"][];
    };
    PostResponseContract: {
      id?: string | null;
      author_id?: string | null;
      is_active?: boolean;
      icon?: string | null;
      banner?: string | null;
      title?: string | null;
      access_key?: string | null;
      description?: string | null;
      excerpt?: string | null;
      gamemode?: components["schemas"]["Gamemode"];
      accessibility?: components["schemas"]["Accessibility"];
      limitations?: components["schemas"]["Limitations"];
      published?: boolean;
      questions?: components["schemas"]["Question"][] | null;
      answers?: components["schemas"]["AnswerContract"][] | null;
      /** Format: date-time */
      publish_time?: string;
    };
    PostUpdateRequestContract: {
      title?: string | null;
      description?: string | null;
      excerpt?: string | null;
      is_active?: boolean;
      gamemode?: components["schemas"]["Gamemode"];
      limitations?: components["schemas"]["Limitations"];
      questions?: components["schemas"]["QuestionUpdateContract"][] | null;
    };
    ProblemDetails: {
      type?: string | null;
      title?: string | null;
      /** Format: int32 */
      status?: number | null;
      detail?: string | null;
      instance?: string | null;
    } & { [key: string]: unknown };
    Question: {
      /** Format: int32 */
      question_id?: number;
      type: components["schemas"]["QuestionType"];
      title: string;
      is_optional?: boolean;
      question_info?: string[] | null;
    };
    /** @enum {string} */
    QuestionType: "Checkbox" | "Freeform" | "Choice";
    QuestionUpdateContract: {
      /** Format: int32 */
      id?: number | null;
      delete?: boolean;
      type?: components["schemas"]["QuestionType"];
      title?: string | null;
      is_optional?: boolean;
      question_info?: string[] | null;
    };
    Submission: {
      /** Format: int32 */
      question_id?: number;
      answer?: string | null;
    };
    SubmissionContract: {
      /** Format: int32 */
      question_id: number;
      question_type: components["schemas"]["QuestionType"];
      answer: string;
    };
    UserMinimalResponseContract: {
      id?: string | null;
      avatar_url?: string | null;
      discord?: string | null;
      username?: string | null;
    };
    UserResponseContract: {
      id?: string | null;
      discord?: string | null;
      osu?: unknown | null;
    };
  };
}

export interface operations {}

export interface external {}
