// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * CircleForms
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * 
 */
export class OAuthApi extends runtime.BaseAPI {

    /**
     * osu! API authentication.
     */
    async oAuthAuthGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/OAuth/auth`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * osu! API authentication.
     */
    async oAuthAuthGet(initOverrides?: RequestInit): Promise<void> {
        await this.oAuthAuthGetRaw(initOverrides);
    }

    /**
     * Sign out from current user. (Requires auth)
     */
    async oAuthSignoutGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/OAuth/signout`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Sign out from current user. (Requires auth)
     */
    async oAuthSignoutGet(initOverrides?: RequestInit): Promise<void> {
        await this.oAuthSignoutGetRaw(initOverrides);
    }

}
